export const FONTS = {
  EXTRA_BOLD:'ExtraBold',
  BOLD: 'Bold',
  SEMI_BOLD: 'SemiBold',
  MEDIUM: 'Medium',
  REGULAR: 'Regular',
  ITALIC: 'Italic',
  LIGHT: 'Light',
  Montserrat_ExtraBold: 'Montserrat_ExtraBold',
  Montserrat_Bold: 'Montserrat_Bold',
  Montserrat_SemiBold: 'Montserrat_SemiBold',
  Montserrat_Medium: 'Montserrat_Medium',
  Montserrat_Regular: 'Montserrat_Regular',
  Montserrat_Light: 'Montserrat_Light',
  Montserrat_Thin: 'Montserrat_Thin',
};

export const FONT_SIZES = {
  XXT: 6,
  XT: 8,
  TINY: 10,
  XS: 12,
  SM: 14,
  BASE: 16,
  LG: 18,
  XL: 20,
  '1XL':22,
  '2XL': 24,
  '3XL': 30,
  '4XL': 36,
  '5XL': 48,
  '6XL': 60,
  '7XL': 72,
  '8XL': 96,
  '9XL': 128,
};
